version: '3.8'
name: 'test_stack'

services:
  far_backend:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    container_name: far_backend_minio
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data